# Generated by Django 3.1.3 on 2020-12-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cpf_hash',
            field=models.IntegerField(null=True),
        ),
    ]
