# Generated by Django 3.1.3 on 2020-12-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_cpf_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf_hash',
            field=models.IntegerField(),
        ),
    ]
