# Generated by Django 3.1.3 on 2020-12-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20201208_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf_hash',
            field=models.CharField(max_length=20),
        ),
    ]
